version: '3.3'
services:
  pawns-database-mysql:
    container_name: pawns-database-mysql
    image: pawns-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'pawns'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'pawns_dev'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'lunaalok'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'lunaalok'
    build: ./docker/pawns-mysql/
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - pawns-db:/var/lib/mysql
# Names our volume
volumes:
  pawns-db: